language: python
python:
  - 3.6
install:
  - pip install -U pip setuptools wheel
  - pip install '.[test]'
script:
  - tox
notifications:
  slack:
    secure: PgikjRmLpuDj7Xe+SRKAaYMLQGgZLjEp1Vou65U2bQUAHtytd+36qtTydxaay5Am+CJlbivYeNQAjBX5bu7/GGG1BTvbLT3EEhoERpMTXifvyAZNS1TzbIW/oOEaIXtU56/xHvtyuBtmPnqt7CzYcuehA88xAzKqWO0DW6mSdBk/q1o5jpJelyGR2m4GXYWSXZKRefYmJDruhI9xGmYuuFPwFmcfd8sdxI4rOUVt5RPiz/XVF2iy0xC4ykt5whVCZD/gUl2YyWMqrtcIaIvRlv+5szPlZ1NQsqAXYaqVDWQ8xA2mOGpK2aFiiJ2dp1BDaEBANjezrMZP2+stBjcWA2xwvwC05Q96lQEilhGIMfa0PjQTiaB2EycwW0xUCoWfNL41AIxoHPVljsmmy2U/Tgiv1UUP+bJ4v/ytY5iSxEk2WT10xsZ/2kbZ98z2go0WSNVHS0omLARYhLgWMR6cdgMLtqy8ZJVWx65XtTibBa0XUaoER+Wqb+a1NyJQ6p0uBP17Fc/gB4IE6eydCIsNsICyn3KkK8AhmTGFnDsMcMxH/2cgo07ixT2ceu2wSsHCingNsWTxQ3zmnqqkyqcdx6u2vJGiaF9kenvpkNjBnQpBtJPDOFNv6frTyI2AGJdb85bMVBZVLc0e7sRHS1IYC4r1W8m1bBsTwO8Df/VY1UY=
