name: Test

on:
  push:

jobs:
  test:
    runs-on: ubuntu-20.04
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
          architecture: 'x64'
      - name: Install packages
        run: |
          pip install -U pip setuptools wheel tox
          pip install '.[test]'
      - name: Run test
        run: tox
